#!/bin/zsh

# compositor
picom \
	-r 12 -o .1 -l -12 -t -12 -c \
	--backend glx --vsync \
	--blur-background \
	--blur-method dual_kawase \
	--blur-strength 10 \
	--no-fading-openclose \
	--experimental-backends \
	--glx-no-stencil \
	--glx-no-rebind-pixmap \
	--use-damage \
	--unredir-if-possible &

# music
mpd &

# hotkeys
sxhkd &

# background
~/.fehbg &

# background cursor
xsetroot -cursor_name left_ptr &

# top panel
#polybar top &

# make screen yellow-ish
redshift -rx
redshift -rO 5000

# bspwm config
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width 0
bspc config window_gap 0
bspc config split_ratio 0.55
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true
